services:
  applications-celery:
    build:
      context: .
      dockerfile: celery_worker/Dockerfile
      platforms:
        - "linux/amd64"
    image: 430118846553.dkr.ecr.us-east-2.amazonaws.com/kora/applications-service:celery-latest